syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

enum AuthMode {
  AUTH_GUEST = 0;
  AUTH_TOKEN = 1;
  AUTH_PUBKEY = 2;
}

enum AuthErrorCode {
  AUTHERR_INTERNAL = 0;
  AUTHERR_BAD_MODE = 1;
  AUTHERR_BAD_CREDENTIAL = 2;
  AUTHERR_RATE_LIMITED = 3;
  AUTHERR_USER_BANNED = 4;
}

enum ErrorCode {
  ERR_INTERNAL = 0;
  ERR_BAD_ID = 1;
  ERR_BAD_METHOD = 2;
  ERR_BAD_INPUT = 3;
  ERR_BAD_STREAM_SEND = 4;
  ERR_STREAM_CLOSED = 5;
  ERR_RATE_LIMITED = 6;
  ERR_NOT_AUTHORIZED = 7;
  ERR_USER = 8;
}

message ServerWelcome {
  uint32 sockrpc = 1;
  string service = 2;
  optional string version = 3;
  optional string userId = 4;
  repeated AuthMode auth = 5;
}

message ClientAuthRequest {
  message Pubkey {
    string userId = 1;
    bytes pubkey = 2;
  }
  oneof request {
    google.protobuf.Empty guest = 1;
    bytes token = 2;
    Pubkey pubkey = 3;
  }
}

message ServerAuthResponse {
  oneof response {
    string userId = 1;
    AuthErrorCode error = 2;
    bytes pubkeyChallenge = 3;
  }
}

message ClientPubkeyChallengeResponse {
  bytes signature = 1;
}

message ClientMessage {
  uint64 id = 1;
  message Call {
    string method = 1;
    bytes request = 2;
    optional google.protobuf.Timestamp deadline = 3;
  }
  message CallClientStream {
    string method = 1;
    optional google.protobuf.Timestamp deadline = 2;
  }
  oneof message {
    Call call = 2;
    CallClientStream callClientStream = 3;
    bytes streamSend = 4;
    google.protobuf.Empty streamClose = 5;
    google.protobuf.Empty abort = 6;
  }
}

message ServerMessage {
  uint64 id = 1;
  message Error {
    ErrorCode code = 1;
    optional string message = 2;
    optional uint32 userErrorCode = 3;
  }
  oneof message {
    Error error = 2;
    bytes callResponse = 3;
    bytes streamRecv = 4;
    google.protobuf.Empty streamClosed = 5;
  }
}
