// @generated by protobuf-ts 2.9.6 with parameter server_generic
// @generated from protobuf file "exampleService.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Number
 */
export interface Number$ {
    /**
     * @generated from protobuf field: int32 n = 1;
     */
    n: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Number$$Type extends MessageType<Number$> {
    constructor() {
        super("Number", [
            { no: 1, name: "n", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Number$>): Number$ {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.n = 0;
        if (value !== undefined)
            reflectionMergePartial<Number$>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Number$): Number$ {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 n */ 1:
                    message.n = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Number$, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 n = 1; */
        if (message.n !== 0)
            writer.tag(1, WireType.Varint).int32(message.n);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Number
 */
export const Number$ = new Number$$Type();
/**
 * @generated ServiceType for protobuf service ExampleService
 */
export const ExampleService = new ServiceType("ExampleService", [
    { name: "Foo", options: {}, I: Number$, O: Number$ },
    { name: "Bar", clientStreaming: true, options: {}, I: Number$, O: Number$ },
    { name: "Baz", serverStreaming: true, options: {}, I: Number$, O: Number$ },
    { name: "Qux", serverStreaming: true, clientStreaming: true, options: {}, I: Number$, O: Number$ }
]);
