// @generated by protobuf-ts 2.9.6 with parameter server_generic
// @generated from protobuf file "exampleService.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ExampleService } from "./exampleService.ts";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { ClientStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Number$ } from "./exampleService.ts";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ExampleService
 */
export interface IExampleServiceClient {
    /**
     * @generated from protobuf rpc: Foo(Number) returns (Number);
     */
    foo(input: Number$, options?: RpcOptions): UnaryCall<Number$, Number$>;
    /**
     * @generated from protobuf rpc: Bar(stream Number) returns (Number);
     */
    bar(options?: RpcOptions): ClientStreamingCall<Number$, Number$>;
    /**
     * @generated from protobuf rpc: Baz(Number) returns (stream Number);
     */
    baz(input: Number$, options?: RpcOptions): ServerStreamingCall<Number$, Number$>;
    /**
     * @generated from protobuf rpc: Qux(stream Number) returns (stream Number);
     */
    qux(options?: RpcOptions): DuplexStreamingCall<Number$, Number$>;
}
/**
 * @generated from protobuf service ExampleService
 */
export class ExampleServiceClient implements IExampleServiceClient, ServiceInfo {
    typeName = ExampleService.typeName;
    methods = ExampleService.methods;
    options = ExampleService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Foo(Number) returns (Number);
     */
    foo(input: Number$, options?: RpcOptions): UnaryCall<Number$, Number$> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Number$, Number$>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Bar(stream Number) returns (Number);
     */
    bar(options?: RpcOptions): ClientStreamingCall<Number$, Number$> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Number$, Number$>("clientStreaming", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: Baz(Number) returns (stream Number);
     */
    baz(input: Number$, options?: RpcOptions): ServerStreamingCall<Number$, Number$> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Number$, Number$>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Qux(stream Number) returns (stream Number);
     */
    qux(options?: RpcOptions): DuplexStreamingCall<Number$, Number$> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Number$, Number$>("duplex", this._transport, method, opt);
    }
}
