// @generated by protobuf-ts 2.9.6 with parameter server_generic
// @generated from protobuf file "exampleService.proto" (syntax proto3)
// tslint:disable
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { RpcOutputStream } from "@protobuf-ts/runtime-rpc";
import { Number$ } from "./exampleService.ts";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ExampleService
 */
export interface IExampleService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: Foo(Number) returns (Number);
     */
    foo(request: Number$, context: T): Promise<Number$>;
    /**
     * @generated from protobuf rpc: Bar(stream Number) returns (Number);
     */
    bar(requests: RpcOutputStream<Number$>, context: T): Promise<Number$>;
    /**
     * @generated from protobuf rpc: Baz(Number) returns (stream Number);
     */
    baz(request: Number$, responses: RpcInputStream<Number$>, context: T): Promise<void>;
    /**
     * @generated from protobuf rpc: Qux(stream Number) returns (stream Number);
     */
    qux(requests: RpcOutputStream<Number$>, responses: RpcInputStream<Number$>, context: T): Promise<void>;
}
